config/routes.rb
Rails.application.routes.draw do
  ################################################################################
  # Root

  root to: 'home#index'

  ################################################################################
  # API

  namespace :api do
    namespace :v2 do
      resources :rubygems, param: :name, only: [], constraints: { name: Patterns::ROUTE_PATTERN } do
        resources :versions, param: :number, only: :show, constraints: {
          number: /#{Gem::Version::VERSION_PATTERN}(?=\.json\z)|#{Gem::Version::VERSION_PATTERN}/
        }
      end
    end

    namespace :v1 do
      resource :api_key, only: :show do
        put :reset
      end
      resources :profiles, only: :show
      resources :downloads, only: :index do
        get :top, on: :collection
        get :all, on: :collection
      end
      constraints id: Patterns::ROUTE_PATTERN, format: /json|yaml/ do
        get 'owners/:handle/gems',
          to: 'owners#gems',
          as: 'owners_gems',
          constraints: { handle: Patterns::ROUTE_PATTERN },
          format: true

        resources :downloads, only: :show, format: true

        resources :versions, only: :show, format: true do
          member do
            get :reverse_dependencies, format: true
            get 'latest',
              to: 'versions#latest',
              as: 'latest',
              format: true,
              constraints: { format: /json|js/ }
          end

          resources :downloads,
            only: [:index],
            controller: 'versions/downloads',
            format: true do
            collection do
              get :search, format: true
            end
          end
        end
      end

      resources :dependencies,
        only: [:index],
        format: /marshal|json/,
        defaults: { format: 'marshal' }

      # for handling preflight request
      match '/gems/:id' => "rubygems#show", via: :options

      resources :rubygems,
        path: 'gems',
        only: [:create, :show, :index],
        id: Patterns::LAZY_ROUTE_PATTERN,
        format: /json|yaml/ do
        member do
          get :reverse_dependencies
        end
        collection do
          delete :yank, to: "deletions#create"
          put :unyank, to: "deletions#destroy"
        end
        constraints rubygem_id: Patterns::ROUTE_PATTERN do
          resource :owners, only: [:show, :create, :destroy]
        end
      end

      resource :activity, only: [], format: /json|yaml/ do
        collection do
          get :latest
          get :just_updated
        end
      end

      resource :search, only: :show

      resources :web_hooks, only: [:create, :index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  get '/versions' => 'api/compact_index#versions'
  get '/info/:gem_name' => 'api/compact_index#info', as: :info,
      constraints: { gem_name: Patterns::ROUTE_PATTERN }
  get '/names' => 'api/compact_index#names'
  ################################################################################
  # API v0

  scope to: 'api/deprecated#index' do
    get 'api_key'
    put 'api_key/reset', to: 'api/deprecated#index'

    post 'gems'
    get 'gems/:id.json'

    scope path: 'gems/:rubygem_id' do
      put 'migrate'
      post 'migrate'
      get 'owners(.:format)'
      post 'owners(.:format)'
      delete 'owners(.:format)'
    end
  end

  ################################################################################
  # UI
  scope constraints: { format: :html }, defaults: { format: 'html' } do
    resource :search,    only: :show
    resource :dashboard, only: :show, constraints: { format: /html|atom/ }
    resources :profiles, only: :show
    resource :profile, only: [:edit, :update]
    resources :stats, only: :index

    resources :rubygems,
      only: [:index, :show, :edit, :update],
      path: 'gems',
      constraints: { id: Patterns::ROUTE_PATTERN, format: /html|atom/ } do
      resource :subscription,
        only: [:create, :destroy],
        constraints: { format: :js },
        defaults: { format: :js }
      resources :versions, only: [:show, :index]
    end
  end

  ################################################################################
  # Clearance Overrides and Additions

  resource :email_confirmations, only: [:new, :create] do
    get 'confirm/:token', to: 'email_confirmations#update', as: :update
  end

  resource :session, only: [:create, :destroy]

  resources :passwords, only: [:new, :create]

  resources :users, only: [:new, :create] do
    resource :password, only: [:create, :edit, :update]
  end

  ################################################################################
  # Internal Routes

  namespace :internal do
    get 'ping' => 'ping#index'
    get 'revision' => 'ping#revision'
  end

  unless Clearance.configuration.allow_sign_up?
    get '/sign_up' => 'users#disabled_signup'
  end
end

app/controllers/api/v1/profiles_controller.rb
class Api::V1::ProfilesController < Api::BaseController
  def show
    @user = User.find_by_slug!(params[:id])
    respond_to do |format|
      format.json { render json: @user }
      format.yaml { render yaml: @user }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :redirect_to_root, unless: :signed_in?, except: :show
  before_action :verify_password, only: :update

  def edit
    @user = current_user
  end

  def show
    @user           = User.find_by_slug!(params[:id])
    rubygems        = @user.rubygems_downloaded
    @rubygems       = rubygems.slice!(0, 10)
    @extra_rubygems = rubygems
  end

  def update
    @user = current_user.clone
    if @user.update_attributes(params_user)
      if @user.unconfirmed?
        Mailer.delay.email_reset(current_user)
        sign_out
        flash[:notice] = "You will receive an email within the next few " \
                         "minutes. It contains instructions for reconfirming " \
                         "your account with your new email address."
        redirect_to_root
      else
        flash[:notice] = "Your profile was updated."
        redirect_to edit_profile_path
      end
    else
      current_user.reload
      render :edit
    end
  end

  private

  def params_user
    params.require(:user).permit(*User::PERMITTED_ATTRS)
  end

  def verify_password
    return if current_user.authenticated?(params[:user][:password])
    flash[:notice] = t('.request_denied')
    redirect_to edit_profile_path
  end
end

app/views/profiles/_rubygem.html.erb
<li class="<%= "small" unless graph %>">
  <a href="<%= rubygem_path(rubygem) %>" class="gems__gem">
    <span class="gems__gem__info">
      <p class="gems__gem__name">
        <%= rubygem.name %>
        <span class="gems__gem__version"><%= rubygem.versions.most_recent %></span>
      </p>
    </span>
    <p class="gems__gem__downloads__count">
      <%= number_with_delimiter(rubygem.downloads) %>
      <span class="gems__gem__downloads__heading">Downloads</span>
    </p>
    <% if graph %>
      <div id="graph-<%= rubygem.id %>" class="profile-graph">
      </div>
    <% end %>
  </a>
</li>

app/views/profiles/edit.html.erb
<% @title = t('.title') %>

<%= form_for @user, :url => {:controller => 'profiles', :action => 'update'} do |form| %>
  <%= form.error_messages %>

  <div class="avatar_field">
    <%= form.label :avatar, :class => 'form__label'  %>
    <div class="l-overflow">
      <%= gravatar(160) %>
      <%= link_to t('.change'), 'https://www.gravatar.com', :class => 't-text t-link' %>
    </div>
  </div>

  <div class="text_field">
    <%= form.label :handle, :class => 'form__label' %>
    <%= form.text_field :handle, :class => 'form__input' %>
  </div>

  <div class="text_field">
    <%= form.label :twitter_username, class: 'form__label form__label__icon-container' do %>
      <%=
        image_tag("/images/twitter_icon.png", alt: 'Twitter icon', class: 'form__label__icon')
      %>
      
      <span class='form__label__text'>Twitter username</span>
    <% end %>

    <p class='form__field__instructions'>
      <%= t('.optional_twitter_username') %>
    </p>

    <div class="form__input__addon-container form__input__addon-left">
      <span class="form__input__addon">@</span>
      <%= form.text_field(:twitter_username, class: 'form__input') %>
    </div>
  </div>

  <div class="text_field">
    <%= form.label :email, :class => 'form__label' %>
    <%= form.email_field :email, :class => 'form__input' %>
  </div>

  <p class='form__field__instructions'>
    <%= t('.enter_password') %>
  </p>
  <div class="password_field">
    <%= form.label :password, :class => 'form__label' %>
    <%= form.password_field :password, :class => 'form__input' %>
  </div>


  <div class="profile-checkbox form__checkbox">
    <%= form.check_box :hide_email, :class => 'form__checkbox__input' %>
    <%= form.label :hide_email, t('.hide_email'), :class => 'form__checkbox__label' %>
  </div>

  <div class="submit_field">
    <%= form.submit 'Update', :data => {:disable_with => t('form_disable_with')}, :class => 'form__submit' %>
  </div>

  <div class="t-body">
    <h2><%= t '.reset_password.title' %></h2>
    <p><%= t('.reset_password.text', :link => link_to(t('.reset_password.link_text'), new_password_url)).html_safe %></p>

    <h2><%= t '.api_access.title' %></h2>
    <p>
      <%= t('.api_access.key_is', :key => content_tag(:strong, current_user.api_key)).html_safe %>
    </p>
    <p>
      <%= t('.api_access.credentials', :gem_credentials_file => content_tag(:code, '~/.gem/credentials'),
                                       :gem_commands_link => link_to(t('.api_access.link_text'), page_url('gem_docs'))).html_safe %>
    </p>
    <pre><code>curl -u <%= current_user.name %> https://rubygems.org/api/v1/api_key.yaml > ~/.gem/credentials; chmod 0600 ~/.gem/credentials</code></pre>
  </div>
<% end %>

<%= button_to t('.api_access.reset'), reset_api_v1_api_key_path, :method => :put, :data => {:confirm => t('.api_access.confirm_reset')}, :class => 'form__submit' %>

app/views/profiles/show.html.erb
<% content_for :title do %>
  <header class="profile__header">
    <div class="profile__header__name-wrap">
      <div id="avatar-frame">
        <%= 
          image_tag(
            @user.gravatar_url(size: 300, secure: request.ssl?).html_safe,
            id: "profile_gravatar",
            width: 300,
            height: 300,
            class: 'profile__header__avatar'
          )
        %>
      </div>

      <h1 id="profile-name" class="profile__header__name t-display">
        <%= 
          link_to(
            @user.display_handle, profile_path(@user.display_id),
            class: "t-link--black"
          )
        %>
      </h1>

      <% unless @user.hide_email %>
        <p id="profile-email">
          <%= 
            mail_to(
              @user.email,
              "Email Me",
              encode: "hex",
              class: "profile__header__attribute t-link--black",
              'data-icon' => '✉'
            )
          %>
        </p>
      <% end %>

      <% if @user.twitter_username.present? %>
        <%=
          image_tag(
            "/images/twitter_icon.png",
            alt: 'Twitter icon',
            class: 'profile__header__icon'
          )
        %>

        <%=
          link_to(
            twitter_username(@user),
            twitter_url(@user),
            class: "profile__header__attribute t-link--black"
          )
        %>
      <% end %>

      <% if @user == current_user %>
        <div id="downloads-ego">
          <%=
            link_to(
              "Edit Profile",
              edit_profile_path,
              id: "edit-profile",
              class: "profile__header__attribute t-link--black"
            )
          %>
        </div>
      <% end %>
    </div>

    <div class="profile__downloads-wrap">
      <h4 class="gem__downloads__heading t-text--s">
        <%= t('stats.index.total_gems') %>
      </h4>

      <h2 id="profile-gems-count" class="gem__downloads">
        <%= @user.total_rubygems_count.to_s %>
      </h2>

      <h4 id="downloads" class="gem__downloads__heading t-text--s">
        <%= t('stats.index.total_downloads') %>
      </h4>

      <h2 id="downloads_count" class="gem__downloads">
        <%= number_with_delimiter(@user.total_downloads_count) %>
      </h2>
    </div>
  </header>
<% end %>

<div id="profile">
  <div class="profile-list">
    <ul>
      <%=
        render(
          partial: 'rubygem',
          collection: @rubygems + @extra_rubygems,
          locals: {graph: false}
        )
      %>
    </ul>
  </div>
</div>