config/routes.rb
Rails.application.routes.draw do
  ################################################################################
  # Root

  root to: 'home#index'

  ################################################################################
  # API

  namespace :api do
    namespace :v2 do
      resources :rubygems, param: :name, only: [], constraints: { name: Patterns::ROUTE_PATTERN } do
        resources :versions, param: :number, only: :show, constraints: {
          number: /#{Gem::Version::VERSION_PATTERN}(?=\.json\z)|#{Gem::Version::VERSION_PATTERN}/
        }
      end
    end

    namespace :v1 do
      resource :api_key, only: :show do
        put :reset
      end
      resources :profiles, only: :show
      resources :downloads, only: :index do
        get :top, on: :collection
        get :all, on: :collection
      end
      constraints id: Patterns::ROUTE_PATTERN, format: /json|yaml/ do
        get 'owners/:handle/gems',
          to: 'owners#gems',
          as: 'owners_gems',
          constraints: { handle: Patterns::ROUTE_PATTERN },
          format: true

        resources :downloads, only: :show, format: true

        resources :versions, only: :show, format: true do
          member do
            get :reverse_dependencies, format: true
            get 'latest',
              to: 'versions#latest',
              as: 'latest',
              format: true,
              constraints: { format: /json|js/ }
          end

          resources :downloads,
            only: [:index],
            controller: 'versions/downloads',
            format: true do
            collection do
              get :search, format: true
            end
          end
        end
      end

      resources :dependencies,
        only: [:index],
        format: /marshal|json/,
        defaults: { format: 'marshal' }

      # for handling preflight request
      match '/gems/:id' => "rubygems#show", via: :options

      resources :rubygems,
        path: 'gems',
        only: [:create, :show, :index],
        id: Patterns::LAZY_ROUTE_PATTERN,
        format: /json|yaml/ do
        member do
          get :reverse_dependencies
        end
        collection do
          delete :yank, to: "deletions#create"
          put :unyank, to: "deletions#destroy"
        end
        constraints rubygem_id: Patterns::ROUTE_PATTERN do
          resource :owners, only: [:show, :create, :destroy]
        end
      end

      resource :activity, only: [], format: /json|yaml/ do
        collection do
          get :latest
          get :just_updated
        end
      end

      resource :search, only: :show

      resources :web_hooks, only: [:create, :index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  get '/versions' => 'api/compact_index#versions'
  get '/info/:gem_name' => 'api/compact_index#info', as: :info,
      constraints: { gem_name: Patterns::ROUTE_PATTERN }
  get '/names' => 'api/compact_index#names'
  ################################################################################
  # API v0

  scope to: 'api/deprecated#index' do
    get 'api_key'
    put 'api_key/reset', to: 'api/deprecated#index'

    post 'gems'
    get 'gems/:id.json'

    scope path: 'gems/:rubygem_id' do
      put 'migrate'
      post 'migrate'
      get 'owners(.:format)'
      post 'owners(.:format)'
      delete 'owners(.:format)'
    end
  end

  ################################################################################
  # UI
  scope constraints: { format: :html }, defaults: { format: 'html' } do
    resource :search,    only: :show
    resource :dashboard, only: :show, constraints: { format: /html|atom/ }
    resources :profiles, only: :show
    resource :profile, only: [:edit, :update]
    resources :stats, only: :index

    resources :rubygems,
      only: [:index, :show, :edit, :update],
      path: 'gems',
      constraints: { id: Patterns::ROUTE_PATTERN, format: /html|atom/ } do
      resource :subscription,
        only: [:create, :destroy],
        constraints: { format: :js },
        defaults: { format: :js }
      resources :versions, only: [:show, :index]
    end
  end

  ################################################################################
  # Clearance Overrides and Additions

  resource :email_confirmations, only: [:new, :create] do
    get 'confirm/:token', to: 'email_confirmations#update', as: :update
  end

  resource :session, only: [:create, :destroy]

  resources :passwords, only: [:new, :create]

  resources :users, only: [:new, :create] do
    resource :password, only: [:create, :edit, :update]
  end

  ################################################################################
  # Internal Routes

  namespace :internal do
    get 'ping' => 'ping#index'
    get 'revision' => 'ping#revision'
  end

  unless Clearance.configuration.allow_sign_up?
    get '/sign_up' => 'users#disabled_signup'
  end
end

app/controllers/api/v1/rubygems_controller.rb
class Api::V1::RubygemsController < Api::BaseController
  skip_before_action :verify_authenticity_token, only: [:create]

  before_action :authenticate_with_api_key, only: [:index, :create]
  before_action :verify_authenticated_user, only: [:index, :create]
  before_action :find_rubygem,              only: [:show]

  before_action :cors_preflight_check, only: :show
  after_action  :cors_set_access_control_headers, only: :show

  def index
    @rubygems = current_user.rubygems.with_versions
    respond_to do |format|
      format.json { render json: @rubygems }
      format.yaml { render yaml: @rubygems }
    end
  end

  def show
    if @rubygem.hosted? && @rubygem.public_versions.indexed.count.nonzero?
      respond_to do |format|
        format.json { render json: @rubygem }
        format.yaml { render yaml: @rubygem }
      end
    else
      render text: t(:this_rubygem_could_not_be_found), status: :not_found
    end
  end

  def create
    gemcutter = Pusher.new(
      current_user,
      request.body,
      request.protocol.delete("://"),
      request.host_with_port
    )
    gemcutter.process
    render text: gemcutter.message, status: gemcutter.code
  rescue => e
    Honeybadger.notify(e)
    render text: "Server error. Please try again.", status: 500
  end

  def reverse_dependencies
    names = begin
      if params[:only] == "development"
        Rubygem.reverse_development_dependencies(params[:id]).pluck(:name)
      elsif params[:only] == "runtime"
        Rubygem.reverse_runtime_dependencies(params[:id]).pluck(:name)
      else
        Rubygem.reverse_dependencies(params[:id]).pluck(:name)
      end
    end

    respond_to do |format|
      format.json { render json: names }
      format.yaml { render yaml: names }
    end
  end

  private

  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'GET'
    headers['Access-Control-Max-Age'] = '1728000'
  end

  def cors_preflight_check
    if request.method == 'OPTIONS'
      cors_set_access_control_headers
      headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'

      render text: '', content_type: 'text/plain'
    end
  end
end

app/controllers/rubygems_controller.rb
class RubygemsController < ApplicationController
  before_action :redirect_to_root, only: [:edit, :update], unless: :signed_in?
  before_action :set_blacklisted_gem, only: [:show], if: :blacklisted?
  before_action :find_rubygem, only: [:edit, :update, :show], unless: :blacklisted?
  before_action :load_gem, only: [:edit, :update]
  before_action :set_page, only: :index

  def index
    respond_to do |format|
      format.html do
        @letter = Rubygem.letterize(params[:letter])
        @gems   = Rubygem.letter(@letter).includes(:latest_version, :gem_download).paginate(page: @page)
      end
      format.atom do
        @versions = Version.published(20)
        render 'versions/feed'
      end
    end
  end

  def show
    if @blacklisted_gem
      render 'blacklisted'
    else
      @latest_version = @rubygem.versions.most_recent
      @versions       = @rubygem.public_versions(5)
      if @rubygem.public_versions.any?
        render 'show'
      else
        render 'show_yanked'
      end
    end
  end

  def edit
  end

  def update
    if @linkset.update_attributes(params_linkset)
      redirect_to rubygem_path(@rubygem)
      flash[:success] = "Gem links updated."
    else
      render :edit
    end
  end

  protected

  def load_gem
    unless @rubygem.owned_by?(current_user)
      flash[:warning] = "You do not have permission to edit this gem."
      redirect_to root_url
    end

    @linkset = @rubygem.linkset
  end

  private

  def blacklisted?
    (Patterns::GEM_NAME_BLACKLIST.include? params[:id].downcase)
  end

  def set_blacklisted_gem
    @blacklisted_gem = params[:id].downcase
  end

  def params_linkset
    params.require(:linkset).permit(:code, :docs, :wiki, :mail, :bugs)
  end
end

app/helpers/rubygems_helper.rb
module RubygemsHelper
  def pluralized_licenses_header(version)
    t("rubygems.show.licenses_header").pluralize(version.try(:licenses).try(:length) || 0)
  end

  def formatted_licenses(license_names)
    if license_names.blank?
      t("rubygems.show.no_licenses")
    else
      Array(license_names).join ", "
    end
  end

  def link_to_page(text, url)
    link_to(text, url, rel: 'nofollow', class: ['gem__link', 't-list__item']) if url.present?
  end

  def link_to_github(rubygem)
    if !rubygem.linkset.code.nil? && URI(rubygem.linkset.code).host == "github.com"
      URI(@rubygem.linkset.code)
    elsif !rubygem.linkset.home.nil? && URI(rubygem.linkset.home).host == "github.com"
      URI(rubygem.linkset.home)
    end
  end

  def link_to_directory
    ("A".."Z").map do |letter|
      link_to(letter, rubygems_path(letter: letter), class: "gems__nav-link")
    end.join("\n").html_safe
  end

  def simple_markup(text)
    if text =~ /^==+ [A-Z]/
      options = RDoc::Options.new
      options.pipe = true
      sanitize RDoc::Markup.new.convert(text, RDoc::Markup::ToHtml.new(options))
    else
      content_tag :p, escape_once(sanitize(text.strip)), nil, false
    end
  end

  def subscribe_link(rubygem)
    if signed_in?
      style = if rubygem.subscribers.find_by_id(current_user.id)
                'display:none'
              else
                'display:inline-block'
              end
      link_to t('.links.subscribe'), rubygem_subscription_path(rubygem),
        class: ['toggler', 'gem__link', 't-list__item'], id: 'subscribe',
        method: :post, remote: true, style: style
    else
      link_to t('.links.subscribe'), sign_in_path,
        class: [:toggler, 'gem__link', 't-list__item'], id: :subscribe
    end
  end

  def unsubscribe_link(rubygem)
    return unless signed_in?
    style = if rubygem.subscribers.find_by_id(current_user.id)
              'display:inline-block'
            else
              'display:none'
            end
    link_to t('.links.unsubscribe'), rubygem_subscription_path(rubygem),
      class: [:toggler, 'gem__link', 't-list__item'], id: 'unsubscribe',
      method: :delete, remote: true, style: style
  end

  def atom_link(rubygem)
    link_to t(".links.rss"), rubygem_versions_path(rubygem, format: 'atom'),
      class: 'gem__link t-list__item', id: :rss
  end

  def download_link(version)
    link_to t('.links.download'), "/downloads/#{version.full_name}.gem",
      class: 'gem__link t-list__item', id: :download
  end

  def documentation_link(version, linkset)
    return unless linkset.nil? || linkset.docs.blank?
    link_to t('.links.docs'), version.documentation_path,
      class: 'gem__link t-list__item', id: :docs
  end

  def badge_link(rubygem)
    badge_url = "https://badge.fury.io/rb/#{rubygem.name}/install"
    link_to t(".links.badge"), badge_url, class: "gem__link t-list__item", id: :badge
  end

  def report_abuse_link(rubygem)
    encoded_title = URI.encode("Reporting Abuse on #{rubygem.name}")
    report_abuse_url = 'http://help.rubygems.org/discussion/new' \
      "?discussion[private]=1&discussion[title]=" + encoded_title
    link_to t(".links.report_abuse"), report_abuse_url.html_safe, class: 'gem__link t-list__item'
  end

  def links_to_owners(rubygem)
    rubygem.owners.sort_by(&:id).map do |owner|
      link_to gravatar(48, "gravatar-#{owner.id}", owner), profile_path(owner.display_id),
        alt: owner.display_handle, title: owner.display_handle
    end.join.html_safe
  end

  def nice_date_for(time)
    time.to_date.to_formatted_s(:long)
  end

  def show_all_versions_link?(rubygem)
    rubygem.versions_count > 5 || rubygem.yanked_versions?
  end

  def latest_version_number(rubygem)
    return rubygem.latest_version_number if rubygem.respond_to?(:latest_version_number)
    (rubygem.latest_version || rubygem.versions.last).try(:number)
  end
end

app/views/rubygems/_dependencies.html.erb
<% if dependencies.present? && @latest_version.indexed %>
  <div class="l-half--l">
    <div class="dependencies" id="<%= dependencies.first.scope %>_dependencies">
      <h3 class="t-list__heading"><%= t '.header', :title => dependencies.first.scope.titleize %> (<%= dependencies_count %>):</h3>
      <div class="t-list__items">
        <% dependencies.each do |dependency| %>
          <% if rubygem = dependency.rubygem %>
            <%= link_to rubygem_path(rubygem), :class => 't-list__item' do %>
              <strong><%= rubygem.name %></strong> <%= dependency.clean_requirements %>
            <% end %>
          <% elsif dependency.try(:name) %>
            <p class="t-list__item gem__unregistered" title="unregistered gem">
              <strong><%= dependency.name %></strong> <%= dependency.clean_requirements %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/rubygems/_gem_members.html.erb
<div class="gem__members">
  <% if latest_version.authors.present? %>
    <h3 class="t-list__heading"><%= t '.authors_header' %>:</h3>
    <ul class="t-list__items">
      <li class="t-list__item">
        <p><%= latest_version.authors %></p>
      </li>
    </ul>
  <% end %>

  <% if rubygem.owners.present? %>
    <h3 class="t-list__heading"><%= t '.owners_header' %>:</h3>
    <div class="gem__owners">
      <%= links_to_owners(rubygem) %>
    </div>
  <% end %>

  <% if latest_version.sha256.present? %>
    <h3 class="t-list__heading"><%= t '.sha_256_checksum' %>:</h3>
    <div class="gem__sha">
      <%= latest_version.sha256_hex %>
    </div>
  <% end %>
</div>

app/views/rubygems/_ruby_version.html.erb
<% if ruby_version.present? %>
  <div class="dependencies" id="ruby_dependency">
    <h5>Ruby Dependency</h5>
    <ol>
      <li>
        <%= ruby_version %>
      </li>
    </ol>
  </div>
<% end %>

app/views/rubygems/_rubygem.html.erb
<%= link_to rubygem_path(rubygem.name), :class => 'gems__gem' do %>
  <span class="gems__gem__info">
    <h2 class="gems__gem__name">
      <%= rubygem.name %>
      <span class="gems__gem__version"><%= latest_version_number(rubygem) %></span>
    </h2>
    <p class="gems__gem__desc t-text"><%= short_info(rubygem) %></p>
  </span>
  <p class="gems__gem__downloads__count">
    <%= download_count rubygem %>
    <span class="gems__gem__downloads__heading">
      <%= t('rubygems.index.downloads') %>
    </span>
  </p>
<% end %>

app/views/rubygems/_version_navigation.html.erb
<div class="gem__navigation">
  <% if latest_version.previous.present? %>
    <%= link_to "← Previous version", rubygem_version_path(rubygem, latest_version.previous.number), class: "gem__previous__version"  %>
  <% end %>

  <% if latest_version.next.present? %>
    <%= link_to "Next version →", rubygem_version_path(rubygem, latest_version.next.number), class: "gem__next__version" %>
  <% end %>
</div>

app/views/rubygems/blacklisted.html.erb
<% @title = @blacklisted_gem %>
<div class="t-body">
  <p><%= t '.blacklisted_namespace' %></p>
</div>

app/views/rubygems/edit.html.erb
<% @title = t('.title') %>
<% @subtitle = t('.subtitle', :gem => @rubygem.name) %>

<div class='t-body'>
  <p><%= t '.other_fields_notice' %></p>
</div>

<%= error_messages_for :linkset, :object_name => "gem" %>
<%= form_for @rubygem.linkset, :url => rubygem_url(@rubygem), :method => :put do |form| %>
  <div class="url_field">
    <%= form.label :code, :class => 'form__label' %>
    <%= form.text_field :code, :class => 'form__input' %>
  </div>
  <div class="url_field">
    <%= form.label :docs, :class => 'form__label' %>
    <%= form.text_field :docs, :class => 'form__input' %>
  </div>
  <div class="url_field">
    <%= form.label :wiki, :class => 'form__label' %>
    <%= form.text_field :wiki, :class => 'form__input' %>
  </div>
  <div class="url_field">
    <%= form.label :mail, :class => 'form__label' %>
    <%= form.text_field :mail, :class => 'form__input' %>
  </div>
  <div class="url_field">
    <%= form.label :bugs, :class => 'form__label' %>
    <%= form.text_field :bugs, :class => 'form__input' %>
  </div>
  <%= form.submit t('update'), :data => {:disable_with => t('form_disable_with')}, :class => 'form__submit' %>
<% end %>

app/views/rubygems/index.html.erb
<% @title = t('.title') %>

<div class="gems__nav-links">
  <%= link_to_directory %>
</div>

<header class="gems__header">
  <p class="gems__meter">
    <%= page_entries_info @gems, :entry_name => 'gem', :model => 'gem' %>
  </p>
</header>

<%= render @gems %>

<%= will_paginate @gems %>

app/views/rubygems/show.html.erb
<% @title = @rubygem.name %>
<% @subtitle = @latest_version.try(:slug) %>

<% content_for :head do %>
  <%= auto_discovery_link_tag(:atom, rubygem_versions_path(@rubygem, format: "atom"), {title: "#{@rubygem.name} Version Feed"}) %>
  <% if @rubygem.versions.present? && @latest_version.indexed %>
    <link rel="canonical" href="<%= rubygem_version_url(@rubygem, @latest_version.slug) %>" />
  <% else %>
    <meta name="robots" content="noindex" />
  <% end %>
<% end %>


<div class="l-overflow">
  <div class="l-colspan--l colspan--l--has-border">
    <% if @latest_version.indexed %>
      <div class="gem__intro">
        <div id="markup" class="gem__desc">
          <%= simple_markup(@latest_version.info) %>
        </div>
      </div>
    <% else %>
      <div class="t-body">
        <p><%=t '.yanked_notice' %></p>
      </div>
    <% end %>

    <% if @versions.present? %>
      <div class="l-half--l">
        <div class="versions">
          <h3 class="t-list__heading"><%= t '.versions_header' %>:</h3>
          <ol class="gem__versions t-list__items">
            <%= render @versions %>
          </ol>
          <% if show_all_versions_link?(@rubygem) %>
            <%= link_to t('.show_all_versions', :count => @rubygem.versions.count), rubygem_versions_url(@rubygem), :class => "gem__see-all-versions t-link--gray t-link--has-arrow" %>
          <% end %>
        </div>
      </div>
    <% end %>

    <%= render :partial => "rubygems/dependencies", :locals => { :dependencies => @latest_version.dependencies.runtime, :dependencies_count => @latest_version.runtime_dependencies_count } %>
    <%= render :partial => "rubygems/dependencies", :locals => { :dependencies => @latest_version.dependencies.development, :dependencies_count => @latest_version.development_dependencies_count } %>

    <% if @latest_version.requirements.present? %>
      <div class="l-half--l">
        <h3 class="t-list__heading"><%= t '.requirements_header' %>:</h3>
        <div class="t-list__items">
          <% Array(@latest_version.requirements).each do |requirement| %>
            <p><%= requirement %></p>
          <% end %>
        </div>
      </div>
    <% end %>

    <%= render partial: "rubygems/gem_members", locals: { latest_version: @latest_version, rubygem: @rubygem } %>
    <%= render partial: "rubygems/version_navigation", locals: { rubygem: @rubygem, latest_version: @latest_version } %>
  </div>

  <div class="gem__aside l-col--r--pad">
    <% if @latest_version.indexed %>
      <div class="gem__downloads-wrap" data-href="<%= api_v1_download_path(@latest_version.full_name, :format => 'json') %>">
        <h2 class="gem__downloads__heading t-text--s">
          <%= t('stats.index.total_downloads') %>
          <span class="gem__downloads"><%= number_with_delimiter(@rubygem.downloads) %></span>
        </h2>
        <h2 class="gem__downloads__heading t-text--s">
          <%= t('.downloads_for_this_version') %>
          <span class="gem__downloads"><%= number_with_delimiter(@latest_version.downloads_count) %></span>
        </h2>
      </div>
    <% end %>

    <% if @latest_version.indexed %>
      <h2 class="gem__ruby-version__heading t-list__heading">
        <%= t '.bundler_header' %>:
        <div class="gem__code-wrap">
          <input type="text" class="gem__code" id="gemfile_text" value="<%= @latest_version.to_bundler %>" readonly="readonly">
          <span class="gem__code__icon" id="js-gem__code--gemfile" data-clipboard-target="#gemfile_text">=</span>
          <span class="gem__code__tooltip--copy"><%= t('.copy_to_clipboard') %></span>
          <span class="gem__code__tooltip--copied"><%= t('.copied') %></span>
        </div>
      </h2>
      <h2 class="gem__ruby-version__heading t-list__heading">
        <%= t '.install' %>:
        <div class="gem__code-wrap">
          <input type="text" class="gem__code" id="install_text" value="<%= @latest_version.to_install %>" readonly="readonly">
          <span class="gem__code__icon" id="js-gem__code--install" data-clipboard-target="#install_text">=</span>
        </div>
      </h2>
      <h2 class="gem__ruby-version__heading t-list__heading">
        <%= pluralized_licenses_header @latest_version %>:
        <span class="gem__ruby-version">
          <p><%= formatted_licenses @latest_version.licenses %></p>
        </span>
      </h2>
    <% end %>

    <h2 class="gem__ruby-version__heading t-list__heading">
      <%= t('.required_ruby_version') %>:
      <i class="gem__ruby-version">
        <% if @latest_version.required_ruby_version %>
          <%= @latest_version.required_ruby_version %>
        <% else %>
          <%= t('none') %>
        <% end %>
      </i>
    </h2>

    <% if @latest_version.required_rubygems_version != '>= 0' %>
      <h2 class="gem__ruby-version__heading t-list__heading">
        <%= t('.required_rubygems_version') %>:
        <i class="gem__ruby-version">
            <%= @latest_version.required_rubygems_version %>
        </i>
      </h2>
    <% end %>

    <h3 class="t-list__heading"><%= t '.links.header' %>:</h3>
    <div class="t-list__items">
      <%= link_to t('edit'), edit_rubygem_path(@rubygem), :class => "gem__link t-list__item", :id => "edit" if @rubygem.owned_by?(current_user) %>

      <% if @latest_version.indexed %>
        <% if @rubygem.linkset.present? %>
          <%- Linkset::LINKS.each do |link| %>
            <%= link_to_page t("rubygems.show.links.#{link}"), @rubygem.linkset.public_send(link) %>
          <%- end %>
        <% end %>

        <%= download_link(@latest_version) %>
      <% end %>

      <%= documentation_link(@latest_version, @rubygem.linkset) %>
      <%= badge_link(@rubygem) %>
      <%= subscribe_link(@rubygem) if @latest_version.indexed %>
      <%= unsubscribe_link(@rubygem) %>
      <%= atom_link(@rubygem) %>
      <%= report_abuse_link(@rubygem) %>
    </div>
  </div>
</div>

app/views/rubygems/show_yanked.html.erb
<% @title = @rubygem.name %>

<% content_for :head do %>
  <meta name="robots" content="noindex" />
<% end %>

<div class="l-overflow">
  <div class="l-colspan--l">
    <div id="markup" class="gem__desc">
      <% if @rubygem.pushable? %>
        <%= t '.not_hosted_notice' %>
      <% else %>
        <%= t('.reserved_namespace', count: @rubygem.protected_days).html_safe %>
      <% end %>
      <%= unsubscribe_link(@rubygem) %>
    </div>

    <% unless @rubygem.pushable? %>
      <%= render partial: "rubygems/gem_members", locals: { latest_version: @latest_version, rubygem: @rubygem } %>
    <% end %>
  </div>
</div>