config/routes.rb
Rails.application.routes.draw do
  ################################################################################
  # Root

  root to: 'home#index'

  ################################################################################
  # API

  namespace :api do
    namespace :v2 do
      resources :rubygems, param: :name, only: [], constraints: { name: Patterns::ROUTE_PATTERN } do
        resources :versions, param: :number, only: :show, constraints: {
          number: /#{Gem::Version::VERSION_PATTERN}(?=\.json\z)|#{Gem::Version::VERSION_PATTERN}/
        }
      end
    end

    namespace :v1 do
      resource :api_key, only: :show do
        put :reset
      end
      resources :profiles, only: :show
      resources :downloads, only: :index do
        get :top, on: :collection
        get :all, on: :collection
      end
      constraints id: Patterns::ROUTE_PATTERN, format: /json|yaml/ do
        get 'owners/:handle/gems',
          to: 'owners#gems',
          as: 'owners_gems',
          constraints: { handle: Patterns::ROUTE_PATTERN },
          format: true

        resources :downloads, only: :show, format: true

        resources :versions, only: :show, format: true do
          member do
            get :reverse_dependencies, format: true
            get 'latest',
              to: 'versions#latest',
              as: 'latest',
              format: true,
              constraints: { format: /json|js/ }
          end

          resources :downloads,
            only: [:index],
            controller: 'versions/downloads',
            format: true do
            collection do
              get :search, format: true
            end
          end
        end
      end

      resources :dependencies,
        only: [:index],
        format: /marshal|json/,
        defaults: { format: 'marshal' }

      # for handling preflight request
      match '/gems/:id' => "rubygems#show", via: :options

      resources :rubygems,
        path: 'gems',
        only: [:create, :show, :index],
        id: Patterns::LAZY_ROUTE_PATTERN,
        format: /json|yaml/ do
        member do
          get :reverse_dependencies
        end
        collection do
          delete :yank, to: "deletions#create"
          put :unyank, to: "deletions#destroy"
        end
        constraints rubygem_id: Patterns::ROUTE_PATTERN do
          resource :owners, only: [:show, :create, :destroy]
        end
      end

      resource :activity, only: [], format: /json|yaml/ do
        collection do
          get :latest
          get :just_updated
        end
      end

      resource :search, only: :show

      resources :web_hooks, only: [:create, :index] do
        collection do
          delete :remove
          post :fire
        end
      end
    end
  end

  get '/versions' => 'api/compact_index#versions'
  get '/info/:gem_name' => 'api/compact_index#info', as: :info,
      constraints: { gem_name: Patterns::ROUTE_PATTERN }
  get '/names' => 'api/compact_index#names'
  ################################################################################
  # API v0

  scope to: 'api/deprecated#index' do
    get 'api_key'
    put 'api_key/reset', to: 'api/deprecated#index'

    post 'gems'
    get 'gems/:id.json'

    scope path: 'gems/:rubygem_id' do
      put 'migrate'
      post 'migrate'
      get 'owners(.:format)'
      post 'owners(.:format)'
      delete 'owners(.:format)'
    end
  end

  ################################################################################
  # UI
  scope constraints: { format: :html }, defaults: { format: 'html' } do
    resource :search,    only: :show
    resource :dashboard, only: :show, constraints: { format: /html|atom/ }
    resources :profiles, only: :show
    resource :profile, only: [:edit, :update]
    resources :stats, only: :index

    resources :rubygems,
      only: [:index, :show, :edit, :update],
      path: 'gems',
      constraints: { id: Patterns::ROUTE_PATTERN, format: /html|atom/ } do
      resource :subscription,
        only: [:create, :destroy],
        constraints: { format: :js },
        defaults: { format: :js }
      resources :versions, only: [:show, :index]
    end
  end

  ################################################################################
  # Clearance Overrides and Additions

  resource :email_confirmations, only: [:new, :create] do
    get 'confirm/:token', to: 'email_confirmations#update', as: :update
  end

  resource :session, only: [:create, :destroy]

  resources :passwords, only: [:new, :create]

  resources :users, only: [:new, :create] do
    resource :password, only: [:create, :edit, :update]
  end

  ################################################################################
  # Internal Routes

  namespace :internal do
    get 'ping' => 'ping#index'
    get 'revision' => 'ping#revision'
  end

  unless Clearance.configuration.allow_sign_up?
    get '/sign_up' => 'users#disabled_signup'
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_with_api_key, unless: :signed_in?
  before_action :redirect_to_root, unless: :signed_in?

  def show
    respond_to do |format|
      format.html do
        @my_gems = current_user.rubygems.with_versions.by_name
        @latest_updates = Version.subscribed_to_by(current_user).published(20)
        @subscribed_gems = current_user.subscribed_gems.with_versions
      end
      format.atom do
        @versions = Version.subscribed_to_by(current_user).published(20)
        render 'versions/feed'
      end
    end
  end
end

app/views/dashboards/show.html.erb
<h1 class="t-display page__heading">Dashboard</h1>

<div class="l-overflow">
  <div class="subscribed l-colspan--l colspan--l--has-border">
    <h3 class="gems__gem__name">
      <%= t '.latest' %>:
    </h3>
    <%= link_to dashboard_url(:api_key => current_user.api_key, :format => :atom), :id => 'feed', :title => t('.latest_title'), :class => 'gem__link t-list__item', 'data-icon' => '#' do %>
      <span class="t-hidden">RSS</span>
    <% end %>
    </a>
    <div class="push--bottom">
      <% if @latest_updates.empty? %>
        <div class="t-body push--s">
          <i class="t-text"><%= t('.no_subscriptions', :gem_link => link_to(t('.gem_link_text'), rubygem_path("rake"))).html_safe %></i>
        </div>
      <% else %>
        <ol>
          <% @latest_updates.each do |version| %>
            <li>
              <a href="<%= rubygem_url(version.rubygem) %>" class="dashboard__gem">
                <div class="dashboard__gem__info">
                  <strong class="dashboard__gem__name"><%= version.to_title %></strong>
                  <i class="dashboard__gem__version"><%= t 'time_ago', :duration => time_ago_in_words(version.created_at) %></i>
                </div>
                <p class="dashboard__gem__desc"><%= short_info(version) %></p>
              </a>
            </li>
          <% end %>
        </ol>
      <% end %>
    </div>
  </div>

  <div class="l-col--r--pad">
    <div class="mine t-body">
      <h1><%= t '.mine' %></h1>
      <% if @my_gems.empty? %>
        <div class="t-body push--bottom">
          <p>
            <%= t('.no_owned', :creating_link => link_to(t('.creating_link_text'), "http://guides.rubygems.org/make-your-own-gem/").html_safe,
                               :migrating_link => link_to(t('.migrating_link_text'), page_url("migrate"))).html_safe %>
          </p>
        </div>
      <% else %>
        <ul>
          <% @my_gems.each do |rubygem| %>
            <li>
              <%= link_to rubygem.name, rubygem, :title => short_info(rubygem.versions.most_recent), :class => 't-link' %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <% if @subscribed_gems.present? %>
        <h1><%= t '.my_subscriptions' %></h1>
        <ul>
          <% current_user.subscribed_gems.each do |gem| %>
            <li>
              <%= link_to gem, gem, :title => short_info(gem.versions.most_recent), :class => 't-link' %>
            </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>